# Generated by Django 5.2.1 on 2025-06-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Введите ваш email', max_length=150, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(help_text='Введите ваше имя', max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Введите вашу фамилию', max_length=150, verbose_name='Фамилия')),
                ('patronymic', models.CharField(help_text='Введите ваше отчество', max_length=100, verbose_name='Отчество')),
                ('comment', models.TextField(help_text='Напишите вам комментарий', verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Напишите тему письма', max_length=200, verbose_name='Тема письма')),
                ('body', models.TextField(help_text='Напишите содержимое письма', verbose_name='Тело письма')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
