# Generated by Django 5.2.1 on 2025-06-05 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_of_first_send', models.DateTimeField()),
                ('datetime_end_of_send', models.DateTimeField()),
                ('is_status', models.CharField(choices=[('Создана', 'Создана'), ('Запущена', 'Запущена'), ('Завершена', 'Завершена')], default='Создана', max_length=20)),
                ('clients', models.ManyToManyField(to='client.client')),
                ('messages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.message')),
            ],
        ),
    ]
